### ISSUE TITLE
정답 만들기

### ISSUE THREAD

**Issue by JakeUGT** [yjh0816/numguess#1]

**Comment by JakeUGT** [comment]
numguess에서 쓰일 정답을 생성합니다.
정답조건: 1~100 사이의 정수

 randint 기능 import하기
 randint 를 활용하여 임의의 정수 생성하기
 생성된 정수를 answer에 할당하기
 (for debugging) console에 출력하기

**Comment by JakeUGT** [comment]
##요약

 - [x] randint 기능 import하기
 - [x] randint 를 활용하여 임의의 정수 생성하기
 - [x] 생성된 정수를 answer에 할당하기
 - [x] (for debugging) console에 출력하기

**Comment by yjh0816** [comment]
good job, do you like soccer?
